server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index pagina1.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /public/ {
        alias /usr/share/nginx/html/public/;
    }

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
